package io.javelin.db.jdbc;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import io.javelin.core.Database;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.stream.Stream;

public final class MigrationRunner {
    private static final ObjectMapper YAML = new ObjectMapper(new YAMLFactory());
    private static final String HISTORY_TABLE = "javelin_migrations";

    private final Database database;
    private final Path migrationsDirectory;

    public MigrationRunner(Database database, Path migrationsDirectory) {
        this.database = Objects.requireNonNull(database, "database");
        this.migrationsDirectory = Objects.requireNonNull(migrationsDirectory, "migrationsDirectory").toAbsolutePath().normalize();
    }

    public List<String> migrate() {
        ensureHistoryTable();
        List<MigrationRecord> applied = appliedMigrations();
        Map<String, MigrationRecord> appliedByName = new LinkedHashMap<>();
        for (MigrationRecord record : applied) {
            appliedByName.put(record.migrationName(), record);
        }
        int batch = nextBatch(applied);
        List<String> ran = new ArrayList<>();
        for (Path file : migrationFiles()) {
            String fileName = file.getFileName().toString();
            if (appliedByName.containsKey(fileName)) {
                continue;
            }
            MigrationFile migration = read(file);
            database.transaction(active -> {
                executeStatements(active, migration.up());
                active.table(HISTORY_TABLE).insert(historyRow(fileName, batch, Instant.now()));
                return null;
            });
            ran.add(migration.name());
        }
        return List.copyOf(ran);
    }

    public List<String> rollback() {
        ensureHistoryTable();
        List<MigrationRecord> applied = appliedMigrations();
        if (applied.isEmpty()) {
            return List.of();
        }
        int latestBatch = applied.stream().map(MigrationRecord::batch).max(Integer::compareTo).orElse(0);
        List<MigrationRecord> batch = applied.stream()
                .filter(record -> record.batch() == latestBatch)
                .sorted(Comparator.comparingLong(MigrationRecord::id).reversed())
                .toList();
        List<String> rolledBack = new ArrayList<>();
        for (MigrationRecord record : batch) {
            Path file = migrationPath(record.migrationName());
            if (!Files.exists(file)) {
                throw new IllegalStateException("Missing migration file: " + file);
            }
            MigrationFile migration = read(file);
            database.transaction(active -> {
                executeStatements(active, migration.down());
                active.table(HISTORY_TABLE)
                        .where("id", record.id())
                        .delete();
                return null;
            });
            rolledBack.add(migration.name());
        }
        return List.copyOf(rolledBack);
    }

    public List<Path> migrationFiles() {
        if (!Files.isDirectory(migrationsDirectory)) {
            return List.of();
        }
        try (Stream<Path> files = Files.list(migrationsDirectory)) {
            return files
                    .filter(Files::isRegularFile)
                    .filter(this::isMigrationFile)
                    .sorted(Comparator.comparing(path -> path.getFileName().toString()))
                    .toList();
        } catch (IOException exception) {
            throw new IllegalStateException("Unable to inspect migrations directory " + migrationsDirectory, exception);
        }
    }

    private void ensureHistoryTable() {
        database.execute("""
                create table if not exists javelin_migrations (
                    id bigint generated by default as identity primary key,
                    migration_name varchar(255) not null unique,
                    batch integer not null,
                    ran_at timestamp not null
                )
                """);
    }

    private List<MigrationRecord> appliedMigrations() {
        List<MigrationRecord> records = new ArrayList<>();
        for (Map<String, Object> row : database.table(HISTORY_TABLE).get()) {
            records.add(MigrationRecord.from(row));
        }
        records.sort(Comparator.comparingLong(MigrationRecord::id));
        return records;
    }

    private int nextBatch(List<MigrationRecord> applied) {
        return applied.stream().map(MigrationRecord::batch).max(Integer::compareTo).orElse(0) + 1;
    }

    private void executeStatements(Database active, List<String> statements) {
        for (String statement : statements) {
            if (statement != null && !statement.isBlank()) {
                active.execute(statement);
            }
        }
    }

    private MigrationFile read(Path file) {
        try {
            Map<String, Object> values = YAML.readValue(Files.readString(file), new TypeReference<>() {
            });
            String name = stringValue(values.getOrDefault("name", baseName(file)));
            List<String> up = statements(values.get("up"));
            List<String> down = statements(values.get("down"));
            return new MigrationFile(name, up, down);
        } catch (IOException exception) {
            throw new IllegalStateException("Unable to read migration " + file, exception);
        }
    }

    private List<String> statements(Object value) {
        if (value == null) {
            return List.of();
        }
        if (value instanceof String text) {
            return List.of(text);
        }
        if (value instanceof List<?> list) {
            List<String> statements = new ArrayList<>();
            for (Object item : list) {
                String statement = extractStatement(item);
                if (!statement.isBlank()) {
                    statements.add(statement);
                }
            }
            return List.copyOf(statements);
        }
        return List.of(extractStatement(value));
    }

    private String extractStatement(Object item) {
        if (item instanceof String text) {
            return text;
        }
        if (item instanceof Map<?, ?> map) {
            return firstNonBlank(map, "sql", "statement", "value");
        }
        return item == null ? "" : item.toString();
    }

    private String firstNonBlank(Map<?, ?> map, String... keys) {
        for (String key : keys) {
            Object value = map.get(key);
            if (value != null && !value.toString().isBlank()) {
                return value.toString();
            }
        }
        return "";
    }

    private Path migrationPath(String migrationName) {
        return migrationsDirectory.resolve(migrationName);
    }

    private boolean isMigrationFile(Path file) {
        String name = file.getFileName().toString().toLowerCase();
        return name.endsWith(".yml") || name.endsWith(".yaml");
    }

    private String baseName(Path file) {
        String name = file.getFileName().toString();
        int dot = name.lastIndexOf('.');
        return dot > 0 ? name.substring(0, dot) : name;
    }

    private String stringValue(Object value) {
        return value == null ? "" : value.toString();
    }

    private Map<String, Object> historyRow(String migrationName, int batch, Instant ranAt) {
        Map<String, Object> row = new LinkedHashMap<>();
        row.put("migration_name", migrationName);
        row.put("batch", batch);
        row.put("ran_at", Timestamp.from(ranAt));
        return row;
    }

    private record MigrationFile(String name, List<String> up, List<String> down) {
    }

    private record MigrationRecord(long id, String migrationName, int batch, Instant ranAt) {
        static MigrationRecord from(Map<String, Object> row) {
            return new MigrationRecord(
                    longValue(row.get("id")),
                    row.getOrDefault("migration_name", "").toString(),
                    intValue(row.get("batch")),
                    instantValue(row.get("ran_at"))
            );
        }

        private static long longValue(Object value) {
            if (value instanceof Number number) {
                return number.longValue();
            }
            if (value instanceof String text && !text.isBlank()) {
                return Long.parseLong(text);
            }
            return 0L;
        }

        private static int intValue(Object value) {
            if (value instanceof Number number) {
                return number.intValue();
            }
            if (value instanceof String text && !text.isBlank()) {
                return Integer.parseInt(text);
            }
            return 0;
        }

        private static Instant instantValue(Object value) {
            if (value instanceof Timestamp timestamp) {
                return timestamp.toInstant();
            }
            if (value instanceof java.util.Date date) {
                return date.toInstant();
            }
            return Instant.EPOCH;
        }
    }
}
