package io.javelin.db.jdbc;

import io.javelin.core.Database;
import io.javelin.core.QueryBuilder;
import io.javelin.core.TransactionCallback;
import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

final class MigrationRunnerTest {
    @Test
    void migratesYamlStatementsAndRecordsHistory() throws Exception {
        Path root = Files.createTempDirectory("javelin-migrations");
        Path migrations = root.resolve("database/migrations");
        Files.createDirectories(migrations);
        Path file = migrations.resolve("20260501010101_create_users.yml");
        Files.writeString(file, """
                name: create_users_table
                up:
                  - sql: |
                      create table users (
                          id bigint generated by default as identity primary key,
                          name varchar(255) not null
                      )
                  - sql: insert into users (name) values ('Alice')
                down:
                  - sql: drop table users
                """);

        RecordingDatabase database = new RecordingDatabase();
        MigrationRunner runner = new MigrationRunner(database, migrations);

        List<String> ran = runner.migrate();

        assertEquals(List.of("create_users_table"), ran);
        assertTrue(database.executedSql.get(0).contains("create table if not exists javelin_migrations"));
        assertTrue(database.executedSql.get(1).contains("create table users"));
        assertEquals("20260501010101_create_users.yml", database.insertedHistory.get(0).get("migration_name"));
        assertEquals(1, database.insertedHistory.get(0).get("batch"));
    }

    @Test
    void rollsBackLatestBatchInReverseHistoryOrder() throws Exception {
        Path root = Files.createTempDirectory("javelin-migrations-rollback");
        Path migrations = root.resolve("database/migrations");
        Files.createDirectories(migrations);

        Path first = migrations.resolve("20260501010101_create_alpha.yml");
        Files.writeString(first, """
                name: create_alpha
                up:
                  - sql: create table alpha (id bigint)
                down:
                  - sql: drop table alpha
                """);
        Path second = migrations.resolve("20260501010102_create_beta.yml");
        Files.writeString(second, """
                name: create_beta
                up:
                  - sql: create table beta (id bigint)
                down:
                  - sql: drop table beta
                """);

        RecordingDatabase database = new RecordingDatabase();
        database.historyRows.add(historyRow(1L, "20260501010101_create_alpha.yml", 5));
        database.historyRows.add(historyRow(2L, "20260501010102_create_beta.yml", 5));
        MigrationRunner runner = new MigrationRunner(database, migrations);

        List<String> rolledBack = runner.rollback();

        assertEquals(List.of("create_beta", "create_alpha"), rolledBack);
        assertEquals(3, database.executedSql.size());
        assertTrue(database.executedSql.get(0).contains("create table if not exists javelin_migrations"));
        assertEquals("drop table beta", database.executedSql.get(1));
        assertEquals("drop table alpha", database.executedSql.get(2));
        assertEquals(List.of(2L, 1L), database.deletedIds);
    }

    private static Map<String, Object> historyRow(long id, String migrationName, int batch) {
        Map<String, Object> row = new LinkedHashMap<>();
        row.put("id", id);
        row.put("migration_name", migrationName);
        row.put("batch", batch);
        row.put("ran_at", Timestamp.from(Instant.parse("2026-05-01T00:00:00Z")));
        return row;
    }

    private static final class RecordingDatabase implements Database {
        private final List<String> executedSql = new ArrayList<>();
        private final List<Map<String, Object>> insertedHistory = new ArrayList<>();
        private final List<Map<String, Object>> historyRows = new ArrayList<>();
        private final List<Long> deletedIds = new ArrayList<>();

        @Override
        public QueryBuilder table(String table) {
            return new RecordingQueryBuilder(table);
        }

        @Override
        public int execute(String sql) {
            executedSql.add(sql.stripIndent().strip());
            return 1;
        }

        @Override
        public <T> T transaction(TransactionCallback<T> callback) {
            try {
                return callback.run(this);
            } catch (Exception exception) {
                throw new IllegalStateException(exception);
            }
        }

        @Override
        public void close() {
        }

        private final class RecordingQueryBuilder implements QueryBuilder {
            private final String table;
            private String whereColumn;
            private Object whereValue;

            private RecordingQueryBuilder(String table) {
                this.table = table;
            }

            @Override
            public QueryBuilder where(String column, Object value) {
                this.whereColumn = column;
                this.whereValue = value;
                return this;
            }

            @Override
            public Optional<Map<String, Object>> first() {
                return historyRows.stream().findFirst().map(LinkedHashMap::new);
            }

            @Override
            public List<Map<String, Object>> get() {
                return historyRows.stream().map(row -> (Map<String, Object>) new LinkedHashMap<>(row)).toList();
            }

            @Override
            public List<Map<String, Object>> paginate(int page, int perPage) {
                return List.of();
            }

            @Override
            public long insert(Map<String, Object> values) {
                if ("javelin_migrations".equals(table)) {
                    insertedHistory.add(new LinkedHashMap<>(values));
                    Map<String, Object> row = new LinkedHashMap<>(values);
                    row.putIfAbsent("id", (long) insertedHistory.size());
                    historyRows.add(row);
                    return insertedHistory.size();
                }
                return 0L;
            }

            @Override
            public int update(Map<String, Object> values) {
                return 0;
            }

            @Override
            public int delete() {
                if (!"javelin_migrations".equals(table) || whereColumn == null) {
                    return 0;
                }
                long id = whereValue instanceof Number number ? number.longValue() : Long.parseLong(whereValue.toString());
                boolean removed = historyRows.removeIf(row -> {
                    Object value = row.get("id");
                    long current = value instanceof Number number ? number.longValue() : Long.parseLong(String.valueOf(value));
                    if (current == id) {
                        deletedIds.add(current);
                        return true;
                    }
                    return false;
                });
                return removed ? 1 : 0;
            }
        }
    }
}
